### ISSUE TITLE
derivation error  and fudge factor

### ISSUE THREAD

**Issue by stephens999** [gaow/pfar#8]
in https://github.com/gaow/dr-tree/blob/a4b12d41e89d2721d65cde53f7900fb21ba47184/writeup/pfar_model.pdf

in section 2.1.1. (best if you label all equations!!)
you need to include the 1/Q for pr(lambda = q)
and can't just ignore it as a constant of proportionality, because
you need the same constant of proportionality to apply for both the nodes and the edges.

That is probably why you found you had to introduce a "fudge factor" - because your derivation
was wrong. I speculate that the fudge factor of Q you introduced actually corresponds to the correct derivation.

**Comment by gaow** [comment]
You are exactly right! The write up you are reading is an earlier version. The recent version has been moved to https://www.overleaf.com/8678042xrmnskhgqjhx where that error was caught and fixed. 

As I commented in this issue, the fudge factor was indeed Q:

https://github.com/gaow/dr-tree/issues/30

The result you see here is exactly what happens with Q = 100:

https://gaow.github.io/dr-tree/doc/documentation/20170328_More_Data_on_Nodes.html#Give-more-weights-to-nodes-13

I have not showed the case when there is no additional data on the nodes. But for that case, using the "correct" derivation does not give as good result as without using it. I can put together a notebook on that.

**Comment by stephens999** [comment]
great.

**Comment by stephens999** [comment]
on terminology: can we agree not to refer to this as a fudge factor any more? 
And not run any without this factor (since it should be there!). Make that the default,
and we will refer to the results as "maximum likelihood" or "standard EM".

**Comment by gaow** [comment]
Sure -- will re-analyze [this page](https://gaow.github.io/dr-tree/doc/documentation/20170324_Fixed_Grid_Weights.html) with the fix, as well as using it for the real data analysis soon to come.

> and we will refer to the results as "maximum likelihood" or "standard EM".

Changed the section title in the write up to "2.1.1 Standard EM" and "2.2.2 Variational EM".
